name: Rust
on:
  pull-requests:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    name: Build, Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: task install
      - run: cargo build --release
      - run: task test
